# Generated by Django 6.0.5 on 2026-05-21 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='clave')),
                ('value', models.TextField(verbose_name='valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuraciones',
                'db_table': '"system"."app_config"',
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='acción')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='datos')),
                ('ip_address', models.TextField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'acción de administrador',
                'verbose_name_plural': 'acciones de administradores',
                'db_table': '"system"."admin_actions_log"',
                'indexes': [models.Index(fields=['admin'], name='admin_actio_admin_i_87d7d7_idx'), models.Index(fields=['created_at'], name='admin_actio_created_afe219_idx')],
            },
        ),
    ]
