# Generated by Django 6.0.5 on 2026-05-21 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, verbose_name='usuario')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='correo')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='teléfono')),
                ('fcm_token', models.TextField(blank=True, null=True, verbose_name='token FCM')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('type_user', models.ForeignKey(db_column='type_user_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.typeuser', verbose_name='tipo de usuario')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': '"core"."users"',
            },
        ),
        migrations.CreateModel(
            name='DicoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='número')),
                ('capacity', models.IntegerField(verbose_name='capacidad')),
                ('table_state', models.ForeignKey(db_column='table_state_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.tablestate', verbose_name='estado')),
                ('table_type', models.ForeignKey(db_column='table_type_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.tabletype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'db_table': '"core"."dico_tables"',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('flyer_url', models.TextField(blank=True, null=True, verbose_name='URL del flyer')),
                ('start_time', models.DateTimeField(verbose_name='inicio')),
                ('end_time', models.DateTimeField(verbose_name='fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('event_state', models.ForeignKey(blank=True, db_column='event_state_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.eventstate', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'db_table': '"core"."events"',
            },
        ),
        migrations.CreateModel(
            name='TablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='table_prices', to='core.event', verbose_name='evento')),
                ('table', models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, related_name='table_prices', to='core.dicotable', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'precio de mesa',
                'verbose_name_plural': 'precios de mesa',
                'db_table': '"core"."table_prices"',
            },
        ),
        migrations.CreateModel(
            name='TypeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('available_quantity', models.IntegerField(verbose_name='cantidad disponible')),
                ('max_override', models.IntegerField(blank=True, null=True, verbose_name='máx. por persona')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='type_tickets', to='core.event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'tipo de ticket',
                'verbose_name_plural': 'tipos de ticket',
                'db_table': '"core"."type_tickets"',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['type_user'], name='users_type_us_8a1a07_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_state'], name='events_event_s_5c64fe_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_start_t_4e5265_idx'),
        ),
        migrations.AddIndex(
            model_name='tableprice',
            index=models.Index(fields=['table'], name='table_price_table_i_813228_idx'),
        ),
        migrations.AddIndex(
            model_name='tableprice',
            index=models.Index(fields=['event'], name='table_price_event_i_40340e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tableprice',
            constraint=models.UniqueConstraint(fields=('table', 'event'), name='uq_table_event_price'),
        ),
        migrations.AddIndex(
            model_name='typeticket',
            index=models.Index(fields=['event'], name='type_ticket_event_i_3a6753_idx'),
        ),
    ]
