# Generated by Django 6.0.5 on 2026-05-21 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de orden')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'órdenes',
                'db_table': '"transactions"."orders"',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado')),
                ('voucher_url', models.TextField(blank=True, null=True, verbose_name='URL del comprobante')),
                ('reference_number', models.TextField(blank=True, null=True, verbose_name='número de referencia')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado en')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='transactions.order', verbose_name='orden')),
                ('payment_method', models.ForeignKey(db_column='payment_method_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.paymentmethod', verbose_name='método de pago')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': '"transactions"."payments"',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='reservado en')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.event', verbose_name='evento')),
                ('reservation_state', models.ForeignKey(db_column='reservation_state_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.reservationstate', verbose_name='estado')),
                ('table', models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.dicotable', verbose_name='mesa')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': '"transactions"."reservations"',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_state', models.ForeignKey(db_column='ticket_state_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.ticketstate', verbose_name='estado')),
                ('type_ticket', models.ForeignKey(db_column='type_ticket_id', on_delete=django.db.models.deletion.PROTECT, to='core.typeticket', verbose_name='tipo de ticket')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': '"transactions"."tickets"',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuento')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='transactions.order', verbose_name='orden')),
                ('table', models.ForeignKey(blank=True, db_column='table_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dicotable', verbose_name='mesa')),
                ('type_ticket', models.ForeignKey(blank=True, db_column='type_ticket_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typeticket', verbose_name='tipo de ticket')),
                ('reservation', models.ForeignKey(blank=True, db_column='reservation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='transactions.reservation', verbose_name='reserva')),
                ('ticket', models.ForeignKey(blank=True, db_column='ticket_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='transactions.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'detalle de orden',
                'verbose_name_plural': 'detalles de orden',
                'db_table': '"transactions"."order_details"',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_user_id_4e08b8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_order_i_b32b33_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user'], name='reservation_user_id_94b298_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table'], name='reservation_table_i_5dd197_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['event'], name='reservation_event_i_e4822f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_state'], name='reservation_reserva_901cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['expires_at'], name='reservation_expires_9dca17_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user'], name='tickets_user_id_3c7de8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['type_ticket'], name='tickets_type_ti_c753b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_state'], name='tickets_ticket__c00729_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['order'], name='order_detai_order_i_4e3e53_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['ticket'], name='order_detai_ticket__56c8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['reservation'], name='order_detai_reserva_46162b_idx'),
        ),
    ]
