# Generated by Django 6.0.5 on 2026-05-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, verbose_name='tabla')),
                ('record_id', models.IntegerField(verbose_name='ID del registro')),
                ('action', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10, verbose_name='acción')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='datos anteriores')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='datos nuevos')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='realizado en')),
            ],
            options={
                'verbose_name': 'log de auditoría',
                'verbose_name_plural': 'logs de auditoría',
                'db_table': '"audit"."audit_logs"',
            },
        ),
    ]
