# Generated by Django 6.0.5 on 2026-05-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'estado de evento',
                'verbose_name_plural': 'estados de evento',
                'db_table': '"catalog"."event_states"',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'estado de orden',
                'verbose_name_plural': 'estados de orden',
                'db_table': '"catalog"."order_statuses"',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'db_table': '"catalog"."payment_methods"',
            },
        ),
        migrations.CreateModel(
            name='ReservationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'estado de reserva',
                'verbose_name_plural': 'estados de reserva',
                'db_table': '"catalog"."reservation_states"',
            },
        ),
        migrations.CreateModel(
            name='TableState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'estado de mesa',
                'verbose_name_plural': 'estados de mesa',
                'db_table': '"catalog"."table_states"',
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de mesa',
                'verbose_name_plural': 'tipos de mesa',
                'db_table': '"catalog"."table_types"',
            },
        ),
        migrations.CreateModel(
            name='TicketState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'estado de ticket',
                'verbose_name_plural': 'estados de ticket',
                'db_table': '"catalog"."ticket_states"',
            },
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de usuario',
                'verbose_name_plural': 'tipos de usuario',
                'db_table': '"catalog"."type_users"',
            },
        ),
    ]
